
services:
  app:
    hostname: rpi-management
    container_name: rpi-management
    build: 
      context: .
    ports:
      - "8000:8000"
    environment:
      - ENV_PATH=/config/dev.env
    volumes:
      - ./monitoring:/monitoring
      - ./config:/config
      - ./data:/vol/web
      - ./keys:/vol/keys
    command: >
      sh -c  "python manage.py wait_for_redis &&
              python manage.py wait_for_db && 
              python manage.py migrate &&
              python manage.py collectstatic --clear --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
  collector:
    build:
      context: .
    container_name: rpi-collector
    environment:
      - ENV_PATH=/config/dev.env
    command: sh -c "python manage.py collect"
    volumes:
      - ./monitoring:/monitoring
      - ./config:/config
      - ./data:/vol/web
      - ./keys:/vol/keys
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=rpi-management
      - MARIADB_USER=rpi-management
      - MARIADB_PASSWORD=changeme
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
