# Generated by Django 5.1.5 on 2025-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('interface', models.CharField(max_length=64)),
                ('mask', models.CharField(max_length=8, null=True)),
                ('physical_address', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('reverse_dns_lookup', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Neighbour',
                'verbose_name_plural': 'Neighbors',
                'unique_together': {('address', 'interface')},
            },
        ),
    ]
