# Generated by Django 5.1.5 on 2025-02-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('interface', models.CharField(max_length=64)),
                ('mask', models.CharField(max_length=8)),
                ('physical_address', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Neighbour',
                'verbose_name_plural': 'Neighbors',
            },
        ),
    ]
