# Generated by Django 5.1.5 on 2025-02-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighborModel',
            new_name='NeighbourModel',
        ),
    ]
