# Generated by Django 5.1.5 on 2025-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_neighbourmodel_mask_alter_neighbourmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'DNS Record',
                'verbose_name_plural': 'DNS Records',
            },
        ),
    ]
