# Generated by Django 5.1.5 on 2025-02-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_dnsrecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecordmodel',
            name='neighbour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.neighbourmodel'),
        ),
    ]
