# Generated by Django 5.1.5 on 2025-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_dnsrecordmodel_neighbour'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourmodel',
            name='status',
            field=models.CharField(default='disconnected', max_length=20),
        ),
    ]
