# Generated by Django 5.1.5 on 2025-02-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_neighbourmodel_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neighbourmodel',
            unique_together={('address', 'interface')},
        ),
    ]
