# Generated by Django 5.1.5 on 2025-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_neighbourmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourmodel',
            name='reverse_dns_lookup',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='DnsRecordModel',
        ),
    ]
