# Generated by Django 5.1.5 on 2025-02-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_neighbourmodel_reverse_dns_lookup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourmodel',
            name='status',
        ),
    ]
