# Generated by Django 5.1.5 on 2025-02-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, null=True)),
                ('used_ram', models.PositiveBigIntegerField(null=True)),
                ('total_ram', models.PositiveBigIntegerField(null=True)),
                ('used_swap', models.PositiveBigIntegerField(null=True)),
                ('total_swap', models.PositiveBigIntegerField(null=True)),
                ('number_of_cpus', models.PositiveSmallIntegerField()),
                ('min_cpu_frequency', models.FloatField(null=True)),
                ('cpu_frequency', models.FloatField(null=True)),
                ('max_cpu_frequency', models.FloatField(null=True)),
                ('cpu_temperature', models.PositiveBigIntegerField(null=True)),
                ('cpu_usage', models.PositiveSmallIntegerField(null=True)),
                ('disk_partitions', models.JSONField(null=True)),
                ('disk_space_available', models.PositiveBigIntegerField(null=True)),
                ('disk_space_total', models.PositiveBigIntegerField(null=True)),
                ('disk_space_used', models.PositiveBigIntegerField(null=True)),
                ('disk_io_read_bytes', models.PositiveBigIntegerField(null=True)),
                ('disk_io_write_bytes', models.PositiveBigIntegerField(null=True)),
                ('net_io_bytes_recv', models.PositiveBigIntegerField(null=True)),
                ('net_io_bytes_sent', models.PositiveBigIntegerField(null=True)),
                ('up_since', models.DateTimeField(null=True)),
                ('time_on_host', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=60)),
                ('processor', models.CharField(max_length=60)),
                ('platform', models.TextField()),
                ('signature', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='SSHConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=60)),
                ('state', models.CharField(default='disconnected', max_length=60)),
                ('session_id', models.CharField(max_length=40, null=True)),
                ('message', models.TextField(null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(default='rpi-monitor', max_length=255)),
                ('monitoring_path', models.CharField(default='/home/rpi-monitor/rpi-monitor', max_length=2048)),
            ],
            options={
                'verbose_name': 'SSH Connection',
                'verbose_name_plural': 'SSH Connections',
            },
        ),
        migrations.CreateModel(
            name='SSHKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('identity_file', models.CharField(max_length=2048)),
                ('public_key', models.TextField()),
            ],
            options={
                'verbose_name': 'SSH Key',
                'verbose_name_plural': 'SSH Keys',
            },
        ),
        migrations.CreateModel(
            name='HostUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_frequency', models.PositiveBigIntegerField(null=True)),
                ('cpu_temperature', models.PositiveBigIntegerField(null=True)),
                ('cpu_usage', models.PositiveBigIntegerField()),
                ('used_ram', models.PositiveBigIntegerField()),
                ('disk_io_read_bytes', models.PositiveBigIntegerField(null=True)),
                ('disk_io_write_bytes', models.PositiveBigIntegerField(null=True)),
                ('net_io_bytes_recv', models.PositiveBigIntegerField(null=True)),
                ('net_io_bytes_sent', models.PositiveBigIntegerField(null=True)),
                ('current_date', models.DateTimeField()),
                ('time_saved', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hostmodel')),
            ],
            options={
                'verbose_name': 'Host Usage',
                'verbose_name_plural': 'Host Usage',
            },
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.platformmodel'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sshconnectionmodel'),
        ),
        migrations.AddField(
            model_name='sshconnectionmodel',
            name='ssh_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sshkeymodel'),
        ),
        migrations.AlterUniqueTogether(
            name='sshconnectionmodel',
            unique_together={('username', 'hostname')},
        ),
    ]
