# Generated by Django 5.1.5 on 2025-02-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='HostInfoModel',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.devicemodel')),
                ('hostname', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=60)),
                ('processor', models.CharField(max_length=60)),
                ('uptime', models.DateTimeField()),
                ('max_frequency', models.PositiveBigIntegerField(null=True)),
                ('total_ram', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Host Infromation',
                'verbose_name_plural': 'Host Infromations',
            },
        ),
        migrations.CreateModel(
            name='SSHConfigurationModel',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.devicemodel')),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('username', models.CharField(max_length=255)),
                ('identity_file', models.CharField(max_length=2048)),
                ('monitoring_path', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name': 'SSH Configuration',
                'verbose_name_plural': 'SSH Configurations',
            },
        ),
        migrations.CreateModel(
            name='DeviceUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_frequency', models.PositiveBigIntegerField(null=True)),
                ('cpu_temperature', models.PositiveBigIntegerField(null=True)),
                ('cpu_usage', models.PositiveBigIntegerField()),
                ('ram_usage', models.PositiveBigIntegerField()),
                ('current_date', models.DateTimeField()),
                ('time_saved', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devicemodel')),
            ],
            options={
                'verbose_name': 'Device Usage',
                'verbose_name_plural': 'Device Usage',
            },
        ),
    ]
