# Generated by Django 5.1.5 on 2025-02-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfomodel',
            old_name='max_frequency',
            new_name='max_cpu_frequency',
        ),
        migrations.RenameField(
            model_name='hostinfomodel',
            old_name='uptime',
            new_name='up_since',
        ),
        migrations.AlterField(
            model_name='sshconfigurationmodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='ssh_conf', serialize=False, to='core.devicemodel'),
        ),
    ]
