# Generated by Django 5.1.5 on 2025-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshconnectionmodel',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
