# Generated by Django 5.1.5 on 2025-02-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sshconnectionmodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshconnectionmodel',
            name='state',
        ),
    ]
