# Generated by Django 5.1.5 on 2025-02-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_max_frequency_hostinfomodel_max_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfomodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='host_info', serialize=False, to='core.devicemodel'),
        ),
        migrations.AlterField(
            model_name='hostinfomodel',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Device Model'),
        ),
    ]
