# Generated by Django 5.1.5 on 2025-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hostmodel_connection_hostruntimemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostruntimemodel',
            name='cpu_frequency',
        ),
        migrations.AlterField(
            model_name='hostruntimemodel',
            name='time_saved',
            field=models.DateTimeField(db_index=True),
        ),
    ]
