# Generated by Django 5.1.5 on 2025-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sshconnectionmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshconnectionmodel',
            name='state',
            field=models.CharField(default='disconnected', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='sshconnectionmodel',
            unique_together={('username', 'hostname')},
        ),
    ]
