# Generated by Django 5.1.5 on 2025-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hostinfomodel_device_alter_hostinfomodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceusagemodel',
            name='time_saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hostinfomodel',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
