# Generated by Django 5.1.5 on 2025-02-18 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_hostruntimemodel_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterfaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('isup', models.BooleanField()),
                ('duplex', models.CharField(max_length=20)),
                ('speed', models.PositiveIntegerField()),
                ('mtu', models.PositiveIntegerField()),
                ('ip4_address', models.CharField(max_length=40, null=True)),
                ('ip6_address', models.CharField(max_length=120, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hostmodel')),
            ],
            options={
                'verbose_name': 'Network Interface',
                'verbose_name_plural': 'Network Interfaces',
                'unique_together': {('host', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=80)),
                ('netmask', models.CharField(max_length=80, null=True)),
                ('broadcast', models.CharField(max_length=80, null=True)),
                ('ptp', models.CharField(max_length=80, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.networkinterfacemodel')),
            ],
            options={
                'verbose_name': 'Network Address',
                'verbose_name_plural': 'Network Addresses',
                'unique_together': {('interface', 'family')},
            },
        ),
    ]
