# Generated by Django 5.1.5 on 2025-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_networkinterfacemodel_interfaceaddressmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterfacemodel',
            name='addresses',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='networkinterfacemodel',
            name='duplex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='networkinterfacemodel',
            name='isup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='networkinterfacemodel',
            name='mtu',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='networkinterfacemodel',
            name='speed',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='InterfaceAddressModel',
        ),
    ]
