# Generated by Django 5.1.5 on 2025-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_deviceusagemodel_time_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='cpu_frequency',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='cpu_temperature',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='cpu_usage',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='used_ram',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
