# Generated by Django 5.1.5 on 2025-02-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_devicemodel_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='cpu_frequency',
            field=models.FloatField(null=True),
        ),
    ]
