# Generated by Django 5.1.5 on 2025-02-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hostmodel_net_io_counters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmodel',
            name='cpu_frequency',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='cpu_temperature',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_io_read_bytes',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_io_write_bytes',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_partitions',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_space_available',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_space_total',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='disk_space_used',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='net_io_bytes_recv',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='net_io_bytes_sent',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='net_io_counters',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='time_on_host',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='total_swap',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='used_ram',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='used_swap',
        ),
    ]
