# Generated by Django 5.1.5 on 2025-02-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hostinfomodel_max_cpu_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfomodel',
            name='platform',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
