# Generated by Django 5.1.5 on 2025-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_hostmodel_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostRuntimeModel',
        ),
    ]
