# Generated by Django 5.1.5 on 2025-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hostinfomodel_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfomodel',
            name='number_of_cpus',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
