# Generated by Django 5.1.5 on 2025-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hostinfomodel_number_of_cpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='disk_space_available',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='disk_space_used',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deviceusagemodel',
            name='disk_space_available',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceusagemodel',
            name='disk_space_used',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
