# Generated by Django 5.1.5 on 2025-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_devicemodel_disk_space_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
