# Generated by Django 5.1.5 on 2025-02-03 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_devicemodel_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('identity_file', models.CharField(max_length=2048)),
                ('public_key', models.TextField()),
            ],
            options={
                'verbose_name': 'SSH Key',
                'verbose_name_plural': 'SSH Keys',
            },
        ),
        migrations.AddField(
            model_name='sshconfigurationmodel',
            name='ssh_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sshkey'),
        ),
    ]
