# Generated by Django 5.1.5 on 2025-02-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sshkey_sshconfigurationmodel_ssh_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSHKey',
            new_name='SSHKeyModel',
        ),
    ]
