# Generated by Django 5.1.5 on 2025-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_sshkey_sshkeymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshconfigurationmodel',
            name='identity_file',
        ),
        migrations.AddField(
            model_name='sshconfigurationmodel',
            name='monitoring_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
