# Generated by Django 5.1.5 on 2025-02-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_sshconfigurationmodel_identity_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceusagemodel',
            old_name='ram_usage',
            new_name='used_ram',
        ),
    ]
