# Generated by Django 5.1.5 on 2025-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_ram_usage_deviceusagemodel_used_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceusagemodel',
            name='time_saved',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
