# Generated by Django 5.1.5 on 2025-02-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_deviceusagemodel_time_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='disk_io_read_bytes',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='disk_io_write_bytes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='net_io_bytes_recv',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='net_io_bytes_sent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='total_swap',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='used_swap',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
