# Generated by Django 5.1.5 on 2025-02-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_deviceusagemodel_disk_io_read_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceusagemodel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.devicemodel'),
        ),
        migrations.AlterField(
            model_name='hostinfomodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='host_info', serialize=False, to='core.devicemodel'),
        ),
        migrations.AlterField(
            model_name='sshconfigurationmodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ssh_conf', serialize=False, to='core.devicemodel'),
        ),
    ]
