# Generated by Django 5.1.5 on 2025-02-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_deviceusagemodel_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfomodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='host_info', serialize=False, to='core.devicemodel'),
        ),
    ]
