# Generated by Django 5.1.5 on 2025-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_hostinfomodel_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='disk_io_write_bytes',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='net_io_bytes_sent',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
