# Generated by Django 5.1.5 on 2025-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_devicemodel_disk_io_write_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfomodel',
            name='up_since',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='time_on_host',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='up_since',
            field=models.DateTimeField(null=True),
        ),
    ]
