# Generated by Django 5.1.5 on 2025-02-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_hostinfomodel_up_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceusagemodel',
            name='disk_io_write_bytes',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceusagemodel',
            name='net_io_bytes_sent',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
