# Generated by Django 5.1.5 on 2025-02-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_deviceusagemodel_disk_io_write_bytes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshconfigurationmodel',
            name='monitoring_url',
        ),
    ]
