# Generated by Django 5.1.5 on 2025-02-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_sshconfigurationmodel_monitoring_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceusagemodel',
            name='disk_space_available',
        ),
        migrations.RemoveField(
            model_name='deviceusagemodel',
            name='disk_space_used',
        ),
        migrations.RemoveField(
            model_name='deviceusagemodel',
            name='total_swap',
        ),
        migrations.RemoveField(
            model_name='deviceusagemodel',
            name='used_swap',
        ),
    ]
