# Generated by Django 5.1.5 on 2025-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_deviceusagemodel_disk_space_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='disk_space_total',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
