# Generated by Django 5.1.5 on 2025-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_devicemodel_disk_space_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='disk_partitions',
            field=models.JSONField(null=True),
        ),
    ]
